# Generated by Django 3.2.7 on 2021-09-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_path',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.CharField(max_length=255),
        ),
    ]
