# Generated by Django 3.2.7 on 2021-09-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210929_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_details', models.FileField(upload_to='')),
                ('image_details', models.FileField(default=False, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
