# Generated by Django 3.2.7 on 2021-09-30 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210929_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subject_taught',
            new_name='subjects_taught',
        ),
    ]
